### ISSUE TITLE
Support for .NET Core?

### ISSUE THREAD

**Issue by mfaizanse** [fluent/NLog.Targets.Fluentd#9]
Hi, my services are in .NET core, Is this sdk supported by .Net core?

**Comment by snakefoot** [comment]
PR is ready: #8

**Comment by moriyoshi** [comment]
The PR was merged.  Can you take a look?

**Comment by snakefoot** [comment]
@moriyoshi Maybe release a nuget-package ?

**Comment by snakefoot** [comment]
Custom NuGet-package, while waiting for the official nuget.org to be updated (net35, net40, net45 + netstandard20)

[NLog.Targets.Fluentd.1.0.5.nupkg.zip](https://github.com/fluent/NLog.Targets.Fluentd/files/1713507/NLog.Targets.Fluentd.1.0.5.nupkg.zip) (Remove zip-extension after download)

**Comment by ghost** [comment]
More than a month has passed and it seems the package hasn't been updated @ Nuget. Can you please check it out? @moriyoshi 

https://www.nuget.org/packages/NLog.Targets.Fluentd/

**Comment by snakefoot** [comment]
@kalexii I'm not the owner of the nuget-package. I just helped with updating the source-code to support NetStandard. Can you verify that the unreleased nuget-package is working for you?

@moriyoshi Maybe time to release as official nuget-package?

**Comment by ghost** [comment]
@snakefoot Well, VS doesn't give me any warnings anymore. I'll follow up once I've wired everything up.
TY for the package 👍

**Comment by ghost** [comment]
@snakefoot 

Matter of fact, it throws some weird error. Here's an excerpt from NLog internal log:

```
2018-03-17 13:25:25.1298 Warn Fluentd Emit - System.IO.IOException: Unable to write data to the transport connection: An established connection was aborted by the software in your host machine. ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at NLog.Targets.FluentdEmitter.Emit(DateTime timestamp, String tag, IDictionary`2 data) in C:\Users\snakefoot\Source\Repos\NLog.Targets.Fluentd\src\NLog.Targets.Fluentd\Fluentd.cs:line 167
   at NLog.Targets.Fluentd.Write(LogEventInfo logEvent) in C:\Users\snakefoot\Source\Repos\NLog.Targets.Fluentd\src\NLog.Targets.Fluentd\Fluentd.cs:line 336
```

And here's my config:

```
<?xml version="1.0" encoding="utf-8"?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="info"
      internalLogFile="c:\temp\internal-nlog.txt">
  <extensions>
    <add assembly="NLog.Targets.Fluentd" />
  </extensions>
  <targets>
    <target xsi:type="Fluentd" name="fluentd-target"
            host="host"
            port="port"
            tag="tag"
            emitStackTraceWhenAvailable="true"
            layout="${longdate}|${event-properties:item=EventId_Id}|${uppercase:${level}}|${logger}|${message} ${exception:format=tostring}|url: ${aspnet-request-url}|action: ${aspnet-mvc-action}" />
  </targets>
  <rules>
    <logger name="*" minlevel="Debug" writeTo="fluentd-target" />
  </rules>
</nlog>
```

That error message is rather misleading, because disabling firewall didn't help.
Running on Windows 10. If it'll can create a sample project to reproduce this, or if you have any pointers to confirmed working sample I can use, I'm all ears :)

**Comment by snakefoot** [comment]
Are you missing something here:

```
            host="host"
            port="port"
```
Have you tried to open a PowerShell-prompt an run this command to check if host and port can be accessed:

`Test-NetConnection -Port 800 -ComputerName 192.168.1.1`

Created #10 that adds some extra logging of connection configuration.

**Comment by ghost** [comment]
@snakefoot I've deliberately replaced actual values with those

**Comment by snakefoot** [comment]
I have created a modified version of the package with support for `SocketOptionName.KeepAlive` and use of  `BufferedStream`. Both are said to help against "connection was aborted"-issues.

[NLog.Targets.Fluentd.1.0.6.nupkg.zip](https://github.com/fluent/NLog.Targets.Fluentd/files/1821903/NLog.Targets.Fluentd.1.0.6.nupkg.zip) (Remove zip-extension after download)

**Comment by ALFNeT** [comment]
Gentle ping to @moriyoshi, would it be possible to update the official nuget package?

**Comment by vthornheart-bng** [comment]
I could use an update to the official nuget package as well.  In a similar boat: I've got a .net core project (in my case, 3.1).

**Comment by chrisdecker1201** [comment]
You can use https://www.nuget.org/packages/NLog.Targets.Fluentd.NetStandard/ which is fork from here https://github.com/jcapellman/NLog.Targets.Fluentd
